# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Beer.create([
  { :name => "Joulutorspo", :style => "Stout", :brewery_id => 1, :created_at => "2013-10-26 18:39:27", :updated_at => "2013-10-26 18:39:27" },
  { :name => "Hello World!", :style => "Lager", :brewery_id => 1, :created_at => "2013-10-26 18:39:27", :updated_at => "2013-10-26 18:39:27" },
  { :name => "Tuplahumala", :style => "Lager", :brewery_id => 1, :created_at => "2013-10-26 18:39:27", :updated_at => "2013-10-26 18:39:27" },
  { :name => "Huvila Pale Ale", :style => "Pale Ale", :brewery_id => 2, :created_at => "2013-10-26 18:39:27", :updated_at => "2013-10-26 18:39:27" },
  { :name => "X Porter", :style => "Porter", :brewery_id => 2, :created_at => "2013-10-26 18:39:27", :updated_at => "2013-10-26 18:39:27" },
  { :name => "Hefezeizen", :style => "Weizen", :brewery_id => 3, :created_at => "2013-10-26 18:39:27", :updated_at => "2013-10-26 18:39:27" },
  { :name => "Helles", :style => "Lager", :brewery_id => 3, :created_at => "2013-10-26 18:39:27", :updated_at => "2013-10-26 18:39:27" },
  { :name => "Ohrapirtelö", :style => "Lager", :brewery_id => 2, :created_at => "2013-10-26 18:48:29", :updated_at => "2013-10-26 18:48:29" },
  { :name => "Punk IPA", :style => "IPA", :brewery_id => 4, :created_at => "2013-10-27 13:00:20", :updated_at => "2013-10-27 13:00:20" },
  { :name => "Nanny State", :style => "low-alcohol", :brewery_id => 4, :created_at => "2013-10-27 13:00:20", :updated_at => "2013-10-27 13:00:20" }
], :without_protection => true )



Brewery.create([
  { :name => "Iken ja Miken Panimo", :year => 2012, :created_at => "2013-10-26 18:39:26", :updated_at => "2013-10-26 18:39:26" },
  { :name => "Malmgard", :year => 2001, :created_at => "2013-10-26 18:39:26", :updated_at => "2013-10-26 18:39:26" },
  { :name => "Weihenstephaner", :year => 1042, :created_at => "2013-10-26 18:39:26", :updated_at => "2013-10-26 18:39:26" },
  { :name => "Brewdog", :year => 2007, :created_at => "2013-10-27 12:58:13", :updated_at => "2013-10-27 12:58:13" }
], :without_protection => true )



Rating.create([
  { :score => 50, :beer_id => 1, :created_at => "2013-10-27 12:55:20", :updated_at => "2013-10-27 12:55:20" },
  { :score => 48, :beer_id => 1, :created_at => "2013-10-27 12:55:46", :updated_at => "2013-10-27 12:55:46" },
  { :score => 46, :beer_id => 1, :created_at => "2013-10-27 12:55:58", :updated_at => "2013-10-27 12:55:58" },
  { :score => 47, :beer_id => 1, :created_at => "2013-10-27 12:56:02", :updated_at => "2013-10-27 12:56:02" },
  { :score => 30, :beer_id => 8, :created_at => "2013-10-27 13:02:11", :updated_at => "2013-10-27 13:02:11" },
  { :score => 34, :beer_id => 8, :created_at => "2013-10-27 13:02:11", :updated_at => "2013-10-27 13:02:11" },
  { :score => 40, :beer_id => 8, :created_at => "2013-10-27 13:02:11", :updated_at => "2013-10-27 13:02:11" },
  { :score => 5, :beer_id => 10, :created_at => "2013-10-27 13:02:55", :updated_at => "2013-10-27 13:02:55" },
  { :score => 15, :beer_id => 10, :created_at => "2013-10-27 13:02:55", :updated_at => "2013-10-27 13:02:55" },
  { :score => 10, :beer_id => 10, :created_at => "2013-10-27 13:02:55", :updated_at => "2013-10-27 13:02:55" }
], :without_protection => true )


